### ISSUE TITLE
Sometimes clicking on the map doesn't work

### ISSUE THREAD

**Issue by leibovic** [leibovic/baby-in-tow#7]
I see this on both Firefox/Chrome, and on Chrome on Android. I consistently see this happen at the default zoom level near the Morning Parade Coffee location (Gerrard and Woodbine).

I did a bit of debugging, and click listeners don't fire on the `ReactMapGL` component at all when this happens (although adding a click listener to the `#container` element shows that firing).

Additionally, on desktop the cursor doesn't change to the pointer or grabber as expected in these cases. So maybe something wonky going on with the DOM?

**Comment by foreverhomes** [comment]
I see the issue! There is a transform applied to the Pin `svg` element and it's separating it from the absolutely positioned `Market` container - the clicks are being intercepted by the Marker div.mapboxgl-marker which isn't forwarding the click. I think the fix is two fold:

1. apply the transform to the Marker, not the pin
2. apply the onClick to the Marker vs on the Pin

I will assign myself!

**Comment by foreverhomes** [comment]
I can't assign myself, haha. But I am happy to fix this.

**Comment by leibovic** [comment]
Sweet, thanks for taking a look! I would of course love if you wanted to fix it 🙇‍♀
